apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: java-springboot-cchhtfio
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/java-springboot-cchhtfio:c1a6a9470884d6a2374b4d26db1ca74d2111ff62@sha256:a14ef007e8b4aaa5558b63a05d8e63b1256e4e9b0e19aa7f4ecacdfc0828dc4d
        name: container-image  
